// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIAkQTvG5fTtWpKZAiAvdlIz3o9vRmUkc',
    appId: '1:413218606481:web:0b4dd57d62bdebdcccde30',
    messagingSenderId: '413218606481',
    projectId: 'firebase-flutter-vitor',
    authDomain: 'fir-flutter-vitor.firebaseapp.com',
    storageBucket: 'firebase-flutter-vitor.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArjDZHxIZ62tGJVbS1-6yLJgRD47qxnzs',
    appId: '1:413218606481:android:34adc7fea6e9a210ccde30',
    messagingSenderId: '413218606481',
    projectId: 'firebase-flutter-vitor',
    storageBucket: 'firebase-flutter-vitor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUm-3PPRe0nGVr9GBEIkjt5IIA-Q4E8lE',
    appId: '1:413218606481:ios:37967b1b20c8e960ccde30',
    messagingSenderId: '413218606481',
    projectId: 'firebase-flutter-vitor',
    storageBucket: 'firebase-flutter-vitor.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUm-3PPRe0nGVr9GBEIkjt5IIA-Q4E8lE',
    appId: '1:413218606481:ios:37967b1b20c8e960ccde30',
    messagingSenderId: '413218606481',
    projectId: 'firebase-flutter-vitor',
    storageBucket: 'firebase-flutter-vitor.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIAkQTvG5fTtWpKZAiAvdlIz3o9vRmUkc',
    appId: '1:413218606481:web:bfc8e26ff7d5a30cccde30',
    messagingSenderId: '413218606481',
    projectId: 'firebase-flutter-vitor',
    authDomain: 'fir-flutter-vitor.firebaseapp.com',
    storageBucket: 'firebase-flutter-vitor.appspot.com',
  );

}